== Die Bibel

=== Einleitung
* Über 1 Milliarde Menschen weltweit bekennen sich zum christlichen Glauben.
* Die meisten sind sich einig, dass die Bibel die maßgebliche Grundlage für ihren Glauben und dessen Ausübung ist.
* Die Bibel wird in 2 anderen großen Weltreligionen als wichtig angesehen: Judentum und Islam
* Sie ist das meistgelesene und einflussreichste Buch.
* Jeder, der eine gute Allgemeinbildung anstrebt, kommt an der Lektüre der Bibel nicht vorbei.

=== Einfluss
* Sie wird von Menschen aus verschiedenen Kulturen, Altersgruppen, Schichten usw. als Grundlage ihres Glaubens betrachtet.
* Sie hat die westliche Kultur tiefgreifend beeinflusst, und die meisten Kulturen der Welt sind auf die eine oder andere Weise von ihr beeinflusst worden.
* Sie besteht aus zwei Hauptteilen

=== Aufbau
Die Bibel besteht aus 2 Teilen: Das Alte und das Neue Testament.
Insgesamt besteht sie aus 66 Büchern von unterschiedlicher Länge.

=== Altes Testament (Tanakh)

* 39 Bücher
* Hauptsächlich auf Hebräisch geschrieben (einige Teile auf Aramäisch)
* Hauptfluss der alttestamentlichen "Geschichte"
** Schöpfung, Adam & Eva, Sündenfall, Verheißung der Wiederherstellung
** Abraham und Beginn der Nation Israel
** Verheißung, dass Elohim die Menschheit durch die abrahamitische Linie erlösen wird
** Beschreibt Elohims Umgang mit der Nation Israel über etwa 2000 Jahre und wie er die Welt auf den kommenden Messias vorbereitet, der die Menschheit erlösen wird
*** Einzelpersonen & Nation
*** Urteile & Gerechtigkeit
*** Weisheit und Macht
*** Barmherzigkeit und Treue
*** Treue, seine Bündnisse zu halten, auch wenn die Menschheit sie bricht
*** Verheißung, besiegelt mit einem Bund, einen Erlöser zu senden, der die Menschheit erlösen und uns in die Beziehung zu Elohim zurückbringen würde

=== Neues Testament (NT)

* 27 Bücher
* Hauptsächlich in griechischer Sprache verfasst
* Einige neuere Manuskripte wurden auch auf Aramäisch gefunden.
* Hauptfluss der NT-"Geschichte"
** Beschreibt das Kommen von Elohims Lösung für das letzte Problem des Menschen in der Person von Jesus Christus, dem Messias
** Messias / Christus - Der Gesalbte
** Erfüllt alles, was im Alten Testament verheißen wurde
** So bilden das Neue und das Alte eine Einheit
** Beschreibt das Leben der ersten Menschen, die erlöst wurden
** Endet mit einem prophetischen Bild vom Ende dieses Zeitalters und dem Beginn einer wunderbaren Ewigkeit, in der die Erlösten als Braut Christi in vollkommener Harmonie mit Elohim leben...
